import { register } from './themes.mjs'

register('straitsx', {
  name: 'StraitsX institutional',
  note: 'A calm institutional payment surface that signals regulated reliability to operators and judges.',
  arc: { cooling: '#0a9b78', void: '#d9363e', settled: '#087f62', lapsed: '#87948f' },
}, `
  :root{--ink:#10231d;--muted:#64756f;--line:#dce8e3;--wash:#f4f9f7;--card:#fff;--green:#087f62;--mint:#dff4ec;--red:#c9363e;--amber:#9a6810;--blue:#1766a7;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
  *,*::before,*::after{box-sizing:border-box}
  body{margin:0;min-height:100vh;background:linear-gradient(180deg,#f7fbf9 0,#eef7f3 100%);color:var(--ink);font:15px/1.55 var(--sans);padding:28px 30px 92px}
  .wrap{max-width:1480px;margin:0 auto}
  .top{display:flex;align-items:flex-end;justify-content:space-between;gap:30px;flex-wrap:wrap;padding:10px 4px 24px;border-bottom:1px solid var(--line);margin-bottom:22px}
  .brand{max-width:820px;font-size:32px;line-height:1.12;font-weight:650;letter-spacing:-.035em;color:#263a33}.brand b{color:var(--green);font-weight:750}
  .tag{margin-top:9px;color:var(--muted);font-size:14px}.tag code{font:12px var(--mono);color:var(--green);background:var(--mint);padding:3px 7px;border-radius:6px}
  .chain{display:flex;gap:30px;text-align:right;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.09em}.chain b{display:block;margin-top:4px;color:var(--ink);font:650 14px/1.25 var(--sans);text-transform:none;letter-spacing:0}.live::before{content:"";display:inline-block;width:8px;height:8px;margin-right:7px;border-radius:50%;background:#13ad82;box-shadow:0 0 0 5px rgba(19,173,130,.12);animation:sxPulse 2s ease-in-out infinite}@keyframes sxPulse{50%{box-shadow:0 0 0 9px rgba(19,173,130,0)}}
  .thesis{max-width:1160px;margin:0 auto 24px;padding:18px 24px;text-align:center;color:#3b5049;font-size:17px;background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:0 8px 30px rgba(19,68,51,.05)}.thesis b{color:var(--green)}
  .rail{display:flex;margin:0 0 7px;background:#fff;border:1px solid var(--line);border-radius:12px;padding:0 10px;box-shadow:0 5px 20px rgba(19,68,51,.04)}
  .railnote{text-align:center;margin:0 0 22px;color:var(--muted);font-size:13px}.railnote i{font-style:normal;color:var(--ink);font-weight:650}
  .step{position:relative;flex:1;min-width:0;padding:14px 12px 13px;border-bottom:3px solid transparent;color:#95a49f}.step+.step::before{content:"";position:absolute;left:0;top:17px;bottom:17px;width:1px;background:var(--line)}.step .n{font-size:10px;line-height:1.2;letter-spacing:.09em;font-weight:750}.step .t{font-size:12.5px;margin-top:3px}.step.done{color:#697d76}.step.done .t{color:#697d76}.step.on{color:var(--green);border-bottom-color:var(--green);background:#f4fbf8}.step.on .t{color:var(--green);font-weight:750}.step.on::after{content:"";position:absolute;left:50%;bottom:-5px;width:7px;height:7px;border-radius:50%;background:var(--green);transform:translateX(-50%)}.step.kill{color:var(--red);border-bottom-color:var(--red)}.step.kill .t{color:var(--red);font-weight:700}.step.fin{color:var(--green);border-bottom-color:#8acdb9}.step.fin .t{color:var(--green);font-weight:700}
  .split{display:grid;grid-template-columns:minmax(0,1fr) 250px minmax(0,1fr);gap:18px;align-items:stretch;margin-bottom:18px}
  .side{display:flex;flex-direction:column;min-width:0;padding:22px 24px;background:var(--card);border:1px solid var(--line);border-radius:16px;box-shadow:0 12px 34px rgba(20,67,52,.07)}.side.merchant{border-top:4px solid #6fa7cf}.side.payer{border-top:4px solid var(--green)}
  .who{color:var(--muted);font-size:11px;line-height:1.2;letter-spacing:.13em;text-transform:uppercase;font-weight:750}.verdictline{min-height:34px;margin:7px 0 10px;font-size:20px;line-height:1.25;font-weight:750}.can{color:var(--green)}.cant{color:var(--red)}.wait{color:var(--amber)}
  .fnote{margin-top:7px;color:#75857f;font:11.5px/1.65 var(--mono)}.fnote b{color:#41564f}
  .quote{margin-top:auto;padding:16px 17px;background:#10231d;color:#fff;border-radius:11px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.07)}.quote .lbl{color:#95b7ab;font:10px/1.4 var(--mono);letter-spacing:.04em;text-transform:uppercase}.quote .said{margin-top:8px;color:#ff9c9f;font:750 21px/1.3 var(--mono);letter-spacing:-.02em;word-break:break-word}.quote .prov{margin-top:9px;color:#8eaaa0;font:10.5px/1.4 var(--mono)}.quote.ok .said{color:#75e4bf}
  button{width:100%;border:0;border-radius:9px;padding:13px 16px;font:750 14px/1.25 var(--sans);letter-spacing:.015em;cursor:pointer;transition:transform .15s,box-shadow .15s,background .15s}button:disabled{cursor:not-allowed;opacity:.55}.bSettle{background:var(--green);color:white;box-shadow:0 7px 16px rgba(8,127,98,.2)}.bSettle.blocked{background:#edf2f0;color:#71827c;box-shadow:none}.bCancel{background:#b92935;color:#fff;box-shadow:0 7px 16px rgba(185,41,53,.16)}.bCancel:hover:not(:disabled){background:#9f202b;transform:translateY(-1px)}
  .ring{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:17px 12px;background:linear-gradient(180deg,#fff,#f2f9f6);border:1px solid var(--line);border-radius:22px;box-shadow:0 12px 34px rgba(20,67,52,.07)}.ringwrap{position:relative;width:170px;height:170px}.ring svg{display:block;transform:rotate(-90deg)}.ring svg circle:first-child{stroke:#dcebe5!important}.ringtxt{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}.ringnum{color:var(--ink);font-size:47px;line-height:1;font-weight:760;letter-spacing:-.045em;font-variant-numeric:tabular-nums}.ringlbl{margin-top:6px;color:var(--green);font-size:10px;font-weight:750;letter-spacing:.14em;text-transform:uppercase}.ringcap{margin-top:12px;color:var(--muted);font-size:11.5px;line-height:1.5;text-align:center}.ringcap b{color:var(--ink);font-weight:750}
  .money{margin-bottom:18px;padding:19px 23px;background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:0 10px 28px rgba(20,67,52,.055)}.money h3{margin:0;color:#758780;font-size:11px;letter-spacing:.14em;text-transform:uppercase}.mrow{display:flex;align-items:center;gap:14px;margin-top:12px;font:13px/1.3 var(--mono)}.mrow .nm{width:132px;color:#53675f}.mrow .bar{height:13px;flex:1;overflow:hidden;background:#edf3f0;border-radius:999px}.mrow .bar i{display:block;height:100%;border-radius:999px;transition:width .6s ease}.mrow.p .bar i{background:linear-gradient(90deg,#0b8063,#21b68c)}.mrow.m .bar i{background:linear-gradient(90deg,#1766a7,#56a1d7)}.mrow .dv{width:78px;text-align:right;color:#81908b;font-size:12px}.mrow .dv.moved{color:var(--green);font-weight:800}.mrow .v{width:126px;text-align:right;color:var(--ink);font-size:14px;font-weight:750}.still{margin-top:13px;color:var(--green);font-size:13px}.still b{font-variant-numeric:tabular-nums;color:#075d49}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{padding:19px 22px;background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:0 10px 28px rgba(20,67,52,.055)}.card h3{margin:0 0 11px;color:#758780;font-size:11px;letter-spacing:.13em;text-transform:uppercase}.piece{display:flex;gap:14px;padding:10px 0;border-bottom:1px solid #e8efec}.piece:last-child{border-bottom:0}.piece .k{width:92px;flex:0 0 auto;font-size:13px;font-weight:800}.piece .d{color:#5c6d67;font-size:12.5px;line-height:1.55}.piece .d code{padding:1px 4px;background:#f1f6f4;border-radius:4px;color:#294b40;font:11.5px var(--mono)}.kX{color:#6652a3}.kA{color:#d53b3d}.kW{color:#a36400}
  .ev{display:flex;align-items:baseline;gap:12px;padding:10px 0;border-bottom:1px solid #e8efec;font:12px/1.45 var(--mono)}.ev .kind{width:184px;flex:0 0 auto;font-weight:800}.ev .used{color:var(--green)}.ev .canc{color:var(--red)}.ev .meta{min-width:0;flex:1;color:#71817b;word-break:break-all}.empty{padding:12px 0;color:#8a9994;font-size:13px}.cta{margin-top:12px;padding:14px 15px;background:#f3f8f6;border:1px solid var(--line);border-radius:9px;color:#687a73;font:12px/1.65 var(--mono)}.cta b{color:var(--green)}a{color:var(--blue);text-decoration:none}a:hover{text-decoration:underline}
  @media(max-width:1000px){body{padding:20px 18px 90px}.split{grid-template-columns:minmax(0,1fr) 220px minmax(0,1fr);gap:12px}.grid2{grid-template-columns:1fr}.side{padding:18px}.rail{overflow-x:auto}.step{min-width:130px}.chain{text-align:left}}
  @media(max-width:720px){body{font-size:15px;padding:16px 12px 90px}.brand{font-size:27px}.chain{width:100%;gap:14px;justify-content:space-between}.chain b{font-size:12px}.thesis{text-align:left;padding:15px 17px}.split{grid-template-columns:1fr}.ring{min-height:250px}.mrow{display:grid;grid-template-columns:1fr auto;gap:7px}.mrow .nm,.mrow .dv,.mrow .v{width:auto}.mrow .bar{grid-column:1/-1;grid-row:2}.mrow .dv{grid-column:1}.mrow .v{grid-column:2}.piece{display:block}.piece .k{width:auto;margin-bottom:4px}.ev{display:block}.ev .kind{width:auto;margin-bottom:4px}}
`)

register('avalanche', {
  name: 'Avalanche infrastructure',
  note: 'A hard-edged infrastructure view that signals speed, finality, and conviction to technical judges.',
  arc: { cooling: '#E84142', void: '#111111', settled: '#168653', lapsed: '#777777' },
}, `
  :root{--red:#E84142;--black:#0b0b0c;--ink:#151516;--paper:#f6f5f1;--white:#fff;--line:#171718;--gray:#626266;--green:#0c7b4d;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;--sans:Impact,"Arial Black","Helvetica Neue",Arial,sans-serif;--body:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
  *,*::before,*::after{box-sizing:border-box}
  body{margin:0;min-height:100vh;background:var(--paper);color:var(--ink);font:15px/1.45 var(--body);padding:24px 26px 90px;background-image:linear-gradient(135deg,rgba(232,65,66,.045) 25%,transparent 25%),linear-gradient(315deg,rgba(232,65,66,.045) 25%,transparent 25%);background-size:36px 36px}
  .wrap{max-width:1540px;margin:0 auto}
  .top{position:relative;display:flex;align-items:flex-end;justify-content:space-between;gap:28px;flex-wrap:wrap;margin-bottom:18px;padding:24px;background:var(--black);color:#fff;border-left:12px solid var(--red);clip-path:polygon(0 0,calc(100% - 30px) 0,100% 30px,100% 100%,0 100%)}
  .brand{max-width:900px;font:800 34px/1.05 var(--sans);letter-spacing:-.025em;text-transform:uppercase}.brand b{display:block;color:var(--red)}.tag{margin-top:10px;color:#b8b8bc;font:13px/1.4 var(--mono)}.tag code{color:#fff;border-bottom:2px solid var(--red)}
  .chain{display:flex;gap:25px;text-align:right;color:#a5a5aa;font:10px/1.3 var(--mono);letter-spacing:.08em;text-transform:uppercase}.chain b{display:block;margin-top:4px;color:#fff;font-size:13px;letter-spacing:0;text-transform:none}.live::before{content:"";display:inline-block;width:9px;height:9px;margin-right:7px;background:var(--red);transform:rotate(45deg);animation:avBlink 1.4s steps(2) infinite}@keyframes avBlink{50%{opacity:.25}}
  .thesis{margin:0 0 18px;padding:18px 22px;background:#fff;border:2px solid var(--line);font-size:17px;font-weight:550;box-shadow:7px 7px 0 rgba(232,65,66,.2)}.thesis b{font-weight:900;text-transform:uppercase;text-decoration:underline;text-decoration-color:var(--red);text-decoration-thickness:4px;text-underline-offset:3px}
  .rail{display:flex;margin:0;background:#fff;border:2px solid var(--line)}.railnote{margin:8px 0 20px;color:#55555a;font:12px/1.45 var(--mono);text-transform:uppercase}.railnote i{font-style:normal;font-weight:800;color:#111}
  .step{position:relative;flex:1;min-width:0;padding:13px 14px;border-right:2px solid var(--line);border-top:7px solid #d5d4d0;color:#8b8b8c}.step:last-child{border-right:0}.step .n{font:900 11px/1.2 var(--sans);letter-spacing:.04em}.step .t{margin-top:3px;font-size:12px}.step.done{border-top-color:#777;color:#555}.step.done .t{color:#555}.step.on{border-top-color:var(--red);color:#111;background:#fff1f1}.step.on .t{color:var(--red);font-weight:900}.step.on::after{content:"";position:absolute;right:9px;top:11px;width:11px;height:11px;background:var(--red);clip-path:polygon(50% 0,100% 100%,0 100%)}.step.kill{border-top-color:#111;color:#111;background:#dedddb}.step.kill .t{color:#111;font-weight:900}.step.fin{border-top-color:var(--green);color:var(--green)}.step.fin .t{color:var(--green);font-weight:900}
  .split{display:grid;grid-template-columns:minmax(0,1fr) 255px minmax(0,1fr);gap:14px;align-items:stretch;margin-bottom:16px}.side{display:flex;flex-direction:column;min-width:0;padding:21px;background:#fff;border:2px solid var(--line)}.side.merchant{box-shadow:inset 0 8px 0 #111}.side.payer{box-shadow:inset 0 8px 0 var(--red)}
  .who{margin-top:7px;color:#656568;font:900 10.5px/1.2 var(--sans);letter-spacing:.1em;text-transform:uppercase}.verdictline{min-height:38px;margin:7px 0 9px;font:900 21px/1.12 var(--sans);text-transform:uppercase}.can{color:var(--green)}.cant{color:var(--red)}.wait{color:#6e5300}.fnote{color:#69696c;font:11px/1.6 var(--mono)}.fnote b{color:#111}
  .quote{position:relative;margin-top:auto;padding:18px 17px 16px;background:#0c0c0d;color:white;border-left:8px solid var(--red)}.quote::after{content:"REJECTED";position:absolute;right:10px;top:7px;color:rgba(232,65,66,.15);font:900 36px/1 var(--sans);transform:rotate(-4deg)}.quote .lbl{position:relative;z-index:1;color:#a2a2a6;font:9.5px/1.4 var(--mono);text-transform:uppercase}.quote .said{position:relative;z-index:1;margin-top:9px;color:#fff;font:800 22px/1.2 var(--mono);letter-spacing:-.035em;word-break:break-word}.quote .said::selection{background:var(--red)}.quote .prov{position:relative;z-index:1;margin-top:10px;color:#e67879;font:10px/1.4 var(--mono)}.quote.ok{border-left-color:var(--green)}.quote.ok .said{color:#61e1a8}
  button{width:100%;padding:14px 16px;border:2px solid #111;border-radius:0;font:900 14px/1.15 var(--sans);letter-spacing:.035em;text-transform:uppercase;cursor:pointer;transition:transform .12s,box-shadow .12s}button:disabled{opacity:.5;cursor:not-allowed}.bSettle{background:#111;color:#fff;box-shadow:5px 5px 0 var(--red)}.bSettle.blocked{background:#d8d7d3;color:#6b6b6b;box-shadow:none}.bCancel{background:var(--red);color:white;box-shadow:5px 5px 0 #111}.bCancel:hover:not(:disabled){transform:translate(3px,3px);box-shadow:2px 2px 0 #111}
  .ring{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:15px 8px;background:var(--red);color:#fff;border:2px solid #111;clip-path:polygon(14px 0,100% 0,100% calc(100% - 14px),calc(100% - 14px) 100%,0 100%,0 14px)}.ringwrap{position:relative;width:170px;height:170px;background:#111;border-radius:50%}.ring svg{display:block;transform:rotate(-90deg)}.ring svg circle:first-child{stroke:#3b3b3d!important}.ringtxt{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column}.ringnum{font:900 50px/1 var(--sans);letter-spacing:-.04em;font-variant-numeric:tabular-nums}.ringlbl{margin-top:4px;color:#c9c9cd;font:800 9px/1.2 var(--body);letter-spacing:.15em;text-transform:uppercase}.ringcap{margin-top:13px;color:#fff;font-size:11.5px;line-height:1.45;text-align:center}.ringcap b{color:#111;background:#fff;padding:1px 4px;font-weight:900}
  .money{margin-bottom:16px;padding:17px 20px;background:#fff;border:2px solid var(--line)}.money h3{margin:0;font:900 12px/1 var(--sans);letter-spacing:.09em;text-transform:uppercase}.mrow{display:flex;align-items:center;gap:13px;margin-top:12px;font:13px/1.2 var(--mono)}.mrow .nm{width:135px;color:#333;font-weight:800;text-transform:uppercase}.mrow .bar{height:16px;flex:1;background:#deddda;border:2px solid #111}.mrow .bar i{display:block;height:100%;transition:width .5s}.mrow.p .bar i{background:var(--red)}.mrow.m .bar i{background:#111}.mrow .dv{width:80px;text-align:right;color:#6a6a6d}.mrow .dv.moved{color:var(--green);font-weight:900}.mrow .v{width:128px;text-align:right;color:#111;font-weight:900}.still{display:inline-block;margin-top:13px;padding:6px 9px;background:#111;color:#fff;font-size:12.5px}.still b{color:#ff7778;font-variant-numeric:tabular-nums}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{padding:18px 20px;background:#fff;border:2px solid var(--line)}.card h3{margin:0 0 10px;padding-bottom:9px;border-bottom:5px solid #111;font:900 12px/1.2 var(--sans);letter-spacing:.07em;text-transform:uppercase}.piece{display:grid;grid-template-columns:100px 1fr;gap:10px;padding:10px 0;border-bottom:2px solid #deddda}.piece:last-child{border-bottom:0}.piece .k{font:900 14px/1.3 var(--sans);text-transform:uppercase}.piece .d{color:#55555a;font-size:12.5px}.piece .d code{color:#111;background:#eeeDEA;padding:2px 4px;font:11px var(--mono)}.kX{color:#6546a9}.kA{color:var(--red)}.kW{color:#986000}
  .ev{display:flex;gap:12px;padding:10px 0;border-bottom:2px solid #deddda;font:12px/1.45 var(--mono)}.ev .kind{width:186px;flex:0 0 auto;font-weight:900}.ev .used{color:var(--green)}.ev .canc{color:var(--red)}.ev .meta{min-width:0;flex:1;color:#66666a;word-break:break-all}.empty{padding:14px 0;color:#777;font:700 13px var(--mono);text-transform:uppercase}.cta{margin-top:12px;padding:13px 14px;background:#e8e7e3;border:2px solid #111;color:#555;font:12px/1.65 var(--mono)}.cta b{color:#111}a{color:var(--red);font-weight:800;text-decoration:underline;text-decoration-thickness:2px}
  @media(max-width:1000px){body{padding:18px 16px 90px}.split{grid-template-columns:minmax(0,1fr) 220px minmax(0,1fr)}.grid2{grid-template-columns:1fr}.rail{overflow-x:auto}.step{min-width:125px}.chain{text-align:left}}
  @media(max-width:720px){body{padding:12px 10px 90px}.top{padding:20px 16px}.brand{font-size:27px}.chain{width:100%;justify-content:space-between;gap:10px}.chain b{font-size:11px}.split{grid-template-columns:1fr}.ring{min-height:260px}.mrow{display:grid;grid-template-columns:1fr auto;gap:7px}.mrow .nm,.mrow .dv,.mrow .v{width:auto}.mrow .bar{grid-column:1/-1;grid-row:2}.mrow .dv{grid-column:1}.mrow .v{grid-column:2}.piece{grid-template-columns:1fr}.ev{display:block}.ev .kind{width:auto;margin-bottom:4px}}
`)

register('editorial', {
  name: 'Editorial ledger',
  note: 'A measured editorial argument that helps policy and product judges read the mechanism as evidence.',
  arc: { cooling: '#b76523', void: '#a12b2b', settled: '#39725a', lapsed: '#8c877d' },
}, `
  :root{--paper:#f4efe5;--paper2:#ebe3d5;--ink:#24221e;--muted:#716b61;--rule:#bdb4a5;--rust:#a94b2a;--green:#356c55;--red:#a12b2b;--blue:#355f81;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;--serif:Georgia,"Times New Roman",serif;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
  *,*::before,*::after{box-sizing:border-box}
  body{margin:0;min-height:100vh;background:var(--paper);color:var(--ink);font:15.5px/1.58 var(--serif);padding:34px 38px 96px;background-image:linear-gradient(rgba(92,75,48,.026) 1px,transparent 1px);background-size:100% 28px}
  .wrap{max-width:1380px;margin:0 auto}
  .top{display:grid;grid-template-columns:1fr auto;gap:34px;align-items:end;margin-bottom:24px;padding:5px 0 18px;border-bottom:4px double var(--ink)}.brand{max-width:900px;font-size:36px;line-height:1.04;letter-spacing:-.03em}.brand b{font-weight:normal;font-style:italic;color:var(--rust)}.tag{margin-top:11px;color:var(--muted);font:12px/1.4 var(--sans);letter-spacing:.055em;text-transform:uppercase}.tag code{font:11px var(--mono);text-transform:none;color:var(--ink)}
  .chain{display:flex;gap:24px;text-align:right;color:var(--muted);font:10.5px/1.3 var(--sans);letter-spacing:.08em;text-transform:uppercase}.chain b{display:block;margin-top:5px;color:var(--ink);font:600 13px/1.2 var(--mono);letter-spacing:0;text-transform:none}.live::before{content:"";display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--green);margin-right:7px;animation:edPulse 2.2s infinite}@keyframes edPulse{50%{opacity:.3}}
  .thesis{max-width:1080px;margin:0 auto 25px;padding:5px 38px 7px;border-left:1px solid var(--rule);border-right:1px solid var(--rule);text-align:center;font-size:19px;line-height:1.55}.thesis::first-letter{font-size:34px;line-height:.8;color:var(--rust)}.thesis b{font-weight:normal;background:linear-gradient(transparent 61%,#dfcdb1 61%)}
  .rail{display:flex;border-top:1px solid var(--ink);border-bottom:1px solid var(--ink)}.railnote{margin:7px 0 24px;color:var(--muted);font:italic 13px/1.5 var(--serif);text-align:right}.railnote i{color:var(--ink);font-style:normal}
  .step{position:relative;flex:1;min-width:0;padding:12px 14px;border-right:1px solid var(--rule);color:#928b80}.step:last-child{border-right:0}.step .n{font:700 9.5px/1.2 var(--sans);letter-spacing:.13em}.step .t{margin-top:3px;font:italic 13px/1.35 var(--serif)}.step.done{color:#726c63}.step.done .t{color:#726c63}.step.on{color:var(--rust);background:rgba(183,101,35,.07)}.step.on .t{color:var(--rust);font-weight:bold}.step.on::after{content:"";position:absolute;left:14px;right:14px;bottom:-2px;height:3px;background:var(--rust)}.step.kill{color:var(--red);background:rgba(161,43,43,.06)}.step.kill .t{color:var(--red);font-weight:bold}.step.fin{color:var(--green)}.step.fin .t{color:var(--green);font-weight:bold}
  .split{display:grid;grid-template-columns:minmax(0,1fr) 250px minmax(0,1fr);gap:0;align-items:stretch;margin-bottom:25px;border-top:1px solid var(--ink);border-bottom:1px solid var(--ink)}.side{display:flex;flex-direction:column;min-width:0;padding:24px 26px}.side.merchant{border-right:1px solid var(--rule)}.side.payer{border-left:1px solid var(--rule)}
  .who{font:700 10px/1.2 var(--sans);letter-spacing:.14em;text-transform:uppercase;color:var(--muted)}.verdictline{min-height:39px;margin:7px 0 10px;font:normal 22px/1.22 var(--serif)}.can{color:var(--green);font-style:italic}.cant{color:var(--red);font-style:italic}.wait{color:#88611e;font-style:italic}.fnote{margin-top:6px;color:#777064;font:11px/1.65 var(--mono)}.fnote b{color:var(--ink)}
  .quote{position:relative;margin-top:auto;padding:17px 18px 15px;background:#27241f;color:#f5efe5;border-top:5px solid var(--rust)}.quote::before{content:"chain evidence";position:absolute;right:12px;top:-20px;color:var(--rust);font:italic 11px var(--serif)}.quote .lbl{color:#bfb5a6;font:9.5px/1.4 var(--mono);text-transform:uppercase}.quote .said{margin-top:9px;color:#ffb39c;font:700 21px/1.3 var(--mono);letter-spacing:-.025em;word-break:break-word}.quote .prov{margin-top:10px;color:#a99f90;font:10px/1.4 var(--mono)}.quote.ok .said{color:#98d4b8}
  button{width:100%;padding:12px 15px;border:1px solid var(--ink);border-radius:0;font:700 12px/1.25 var(--sans);letter-spacing:.1em;text-transform:uppercase;cursor:pointer;background:transparent;color:var(--ink);transition:background .15s,color .15s}button:disabled{opacity:.45;cursor:not-allowed}.bSettle{background:var(--ink);color:var(--paper)}.bSettle.blocked{background:transparent;color:#888176;border-color:#aaa194}.bCancel{background:var(--red);border-color:var(--red);color:#fff}.bCancel:hover:not(:disabled){background:#7f1f1f}
  .ring{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px 10px;background:var(--paper2)}.ringwrap{position:relative;width:170px;height:170px}.ring svg{display:block;transform:rotate(-90deg)}.ring svg circle:first-child{stroke:#d3c9b9!important;stroke-width:4!important}.ringtxt{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}.ringnum{font-size:50px;line-height:1;font-variant-numeric:tabular-nums;letter-spacing:-.045em}.ringlbl{margin-top:5px;color:var(--muted);font:700 9px/1.2 var(--sans);letter-spacing:.14em;text-transform:uppercase}.ringcap{margin-top:12px;color:var(--muted);font:italic 12px/1.5 var(--serif);text-align:center}.ringcap b{color:var(--ink);font-style:normal;font-weight:normal;border-bottom:1px solid var(--ink)}
  .money{margin-bottom:24px;padding:0 0 17px;border-top:4px double var(--ink);border-bottom:1px solid var(--ink)}.money h3{display:inline-block;margin:0 0 3px;padding:6px 10px 5px;background:var(--ink);color:var(--paper);font:700 10px/1 var(--sans);letter-spacing:.13em;text-transform:uppercase}.mrow{display:flex;align-items:center;gap:14px;margin-top:12px;font:12.5px/1.3 var(--mono)}.mrow .nm{width:138px;color:var(--ink);font-family:var(--serif);font-size:14px}.mrow .bar{height:8px;flex:1;background:#d8cfc0}.mrow .bar i{display:block;height:100%;transition:width .6s ease}.mrow.p .bar i{background:var(--green)}.mrow.m .bar i{background:var(--blue)}.mrow .dv{width:78px;text-align:right;color:#81796e}.mrow .dv.moved{color:var(--green);font-weight:bold}.mrow .v{width:128px;text-align:right;color:var(--ink);font-weight:bold}.still{margin-top:12px;color:var(--green);font-style:italic}.still b{font-style:normal;font-variant-numeric:tabular-nums}
  .grid2{display:grid;grid-template-columns:1.15fr .85fr;gap:34px}.card{padding-top:3px;border-top:1px solid var(--ink)}.card h3{margin:0 0 8px;padding:7px 0;border-bottom:1px solid var(--rule);font:700 10px/1.2 var(--sans);letter-spacing:.13em;text-transform:uppercase}.piece{display:grid;grid-template-columns:96px 1fr;gap:13px;padding:10px 0;border-bottom:1px solid var(--rule)}.piece:last-child{border-bottom:0}.piece .k{font:700 13px/1.35 var(--sans)}.piece .d{color:#5f594f;font-size:13px}.piece .d code{color:#423d35;font:11.5px var(--mono);border-bottom:1px dotted #8d8273}.kX{color:#684f93}.kA{color:#b23331}.kW{color:#8b621b}
  .ev{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid var(--rule);font:11.5px/1.5 var(--mono)}.ev .kind{width:185px;flex:0 0 auto;font-weight:bold}.ev .used{color:var(--green)}.ev .canc{color:var(--red)}.ev .meta{min-width:0;flex:1;color:#736c62;word-break:break-all}.empty{padding:13px 0;color:#847c70;font-style:italic}.cta{margin-top:12px;padding:13px 15px;border:1px solid var(--rule);color:#6f675c;font:11.5px/1.65 var(--mono)}.cta b{color:var(--ink)}a{color:var(--blue);text-decoration-thickness:1px;text-underline-offset:2px}
  @media(max-width:1000px){body{padding:24px 22px 92px}.split{grid-template-columns:minmax(0,1fr) 220px minmax(0,1fr)}.grid2{grid-template-columns:1fr}.rail{overflow-x:auto}.step{min-width:125px}.top{grid-template-columns:1fr}.chain{text-align:left}}
  @media(max-width:720px){body{padding:18px 14px 92px}.brand{font-size:30px}.chain{justify-content:space-between;gap:11px}.chain b{font-size:11px}.thesis{text-align:left;padding:5px 18px}.split{grid-template-columns:1fr}.side.merchant{border-right:0;border-bottom:1px solid var(--rule)}.side.payer{border-left:0;border-top:1px solid var(--rule)}.ring{min-height:255px}.mrow{display:grid;grid-template-columns:1fr auto;gap:7px}.mrow .nm,.mrow .dv,.mrow .v{width:auto}.mrow .bar{grid-column:1/-1;grid-row:2}.mrow .dv{grid-column:1}.mrow .v{grid-column:2}.piece{grid-template-columns:1fr}.ev{display:block}.ev .kind{width:auto;margin-bottom:3px}}
`)

register('console', {
  name: 'Layered console',
  note: 'A disciplined live-operations surface that gives engineers depth, hierarchy, and trustworthy machine evidence.',
  arc: { cooling: '#f4b860', void: '#ff6577', settled: '#4dd7a0', lapsed: '#677487' },
}, `
  :root{--bg:#080d15;--surface:#0e1622;--raised:#141f2e;--deep:#090f18;--line:#233146;--line2:#33445d;--text:#edf3fb;--muted:#8b9aaf;--faint:#617087;--green:#4dd7a0;--red:#ff6577;--amber:#f4b860;--cyan:#61bafc;--violet:#b39cff;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
  *,*::before,*::after{box-sizing:border-box}
  body{margin:0;min-height:100vh;background:radial-gradient(circle at 50% -20%,#19304a 0,transparent 43%),linear-gradient(180deg,#090f18,#070b12);color:var(--text);font:15px/1.5 var(--sans);padding:25px 28px 92px}
  .wrap{max-width:1510px;margin:0 auto}
  .top{display:flex;align-items:flex-end;justify-content:space-between;gap:30px;flex-wrap:wrap;margin-bottom:20px;padding:17px 19px;background:rgba(14,22,34,.84);border:1px solid var(--line);border-radius:14px;box-shadow:0 16px 55px rgba(0,0,0,.28),inset 0 1px rgba(255,255,255,.035)}.brand{max-width:900px;color:#bac5d4;font-size:29px;line-height:1.13;font-weight:600;letter-spacing:-.03em}.brand b{color:#fff;font-weight:750}.tag{margin-top:8px;color:var(--muted);font-size:13px}.tag code{padding:3px 6px;border:1px solid #30445d;border-radius:5px;color:var(--cyan);font:11px var(--mono)}
  .chain{display:flex;gap:27px;text-align:right;color:var(--faint);font:10px/1.3 var(--mono);letter-spacing:.09em;text-transform:uppercase}.chain b{display:block;margin-top:5px;color:#dfe8f3;font-size:13px;font-weight:550;letter-spacing:0;text-transform:none}.live::before{content:"";display:inline-block;width:7px;height:7px;margin-right:7px;border-radius:50%;background:var(--green);box-shadow:0 0 12px var(--green);animation:coLive 2s infinite}@keyframes coLive{50%{opacity:.35;box-shadow:0 0 4px var(--green)}}
  .thesis{margin:0 0 20px;padding:15px 19px;background:linear-gradient(90deg,rgba(97,186,252,.1),rgba(77,215,160,.035));border:1px solid #263b53;border-left:4px solid var(--cyan);border-radius:9px;color:#b9c7d8;font-size:16px}.thesis b{color:#fff;font-weight:700}
  .rail{display:flex;margin:0 0 6px;padding:5px;background:var(--deep);border:1px solid var(--line);border-radius:10px}.railnote{margin:0 0 19px;color:var(--faint);font:11.5px/1.45 var(--mono);text-align:center}.railnote i{color:#bdcad9;font-style:normal}
  .step{position:relative;flex:1;min-width:0;padding:10px 12px;border-radius:6px;color:#56657a}.step .n{font:650 9.5px/1.2 var(--mono);letter-spacing:.08em}.step .t{margin-top:3px;font-size:12px}.step.done{color:#7b8da5}.step.done .t{color:#7b8da5}.step.on{color:var(--amber);background:#1c2634;box-shadow:inset 0 0 0 1px #3f4853}.step.on .t{color:#ffe1ad;font-weight:700}.step.on::after{content:"";position:absolute;right:10px;top:11px;width:6px;height:6px;border-radius:50%;background:var(--amber);box-shadow:0 0 9px var(--amber);animation:coLive 1.4s infinite}.step.kill{color:var(--red);background:rgba(255,101,119,.09)}.step.kill .t{color:#ff9ba7}.step.fin{color:var(--green);background:rgba(77,215,160,.07)}.step.fin .t{color:#84e7bf}
  .split{display:grid;grid-template-columns:minmax(0,1fr) 258px minmax(0,1fr);gap:16px;align-items:stretch;margin-bottom:17px}.side{display:flex;flex-direction:column;min-width:0;padding:20px;background:linear-gradient(155deg,var(--raised),var(--surface));border:1px solid var(--line);border-radius:13px;box-shadow:0 18px 44px rgba(0,0,0,.2),inset 0 1px rgba(255,255,255,.03)}.side.merchant{border-top:2px solid var(--cyan)}.side.payer{border-top:2px solid var(--violet)}
  .who{color:var(--muted);font:650 10px/1.2 var(--mono);letter-spacing:.12em;text-transform:uppercase}.verdictline{min-height:35px;margin:7px 0 10px;font-size:19px;line-height:1.25;font-weight:720;letter-spacing:-.01em}.can{color:var(--green)}.cant{color:var(--red)}.wait{color:var(--amber)}.fnote{margin-top:7px;color:var(--faint);font:11px/1.65 var(--mono)}.fnote b{color:#aab8ca;font-weight:600}
  .quote{position:relative;margin-top:auto;padding:17px 18px 15px;background:#05090f;border:1px solid #354157;border-radius:9px;box-shadow:0 12px 30px rgba(0,0,0,.3),inset 0 0 35px rgba(255,101,119,.035)}.quote::before{content:"";position:absolute;left:-1px;top:13px;bottom:13px;width:3px;background:var(--red);box-shadow:0 0 10px rgba(255,101,119,.5)}.quote .lbl{color:#78889d;font:9.5px/1.4 var(--mono);letter-spacing:.04em;text-transform:uppercase}.quote .said{margin-top:9px;color:#ff8493;font:700 21px/1.28 var(--mono);letter-spacing:-.025em;text-shadow:0 0 18px rgba(255,101,119,.18);word-break:break-word}.quote .prov{margin-top:10px;color:#66758a;font:10px/1.4 var(--mono)}.quote.ok::before{background:var(--green)}.quote.ok .said{color:#79e5bb}
  button{width:100%;padding:13px 16px;border:1px solid transparent;border-radius:8px;font:700 13px/1.2 var(--sans);letter-spacing:.025em;cursor:pointer;transition:transform .15s,filter .15s,box-shadow .15s}button:disabled{opacity:.45;cursor:not-allowed}.bSettle{background:var(--cyan);color:#06131f;box-shadow:0 7px 20px rgba(97,186,252,.18)}.bSettle.blocked{background:#1a2534;border-color:#2d3c50;color:#738299;box-shadow:none}.bCancel{background:linear-gradient(180deg,#ff7181,#e94f63);color:#1d0509;box-shadow:0 8px 22px rgba(255,101,119,.18)}.bCancel:hover:not(:disabled){filter:brightness(1.08);transform:translateY(-1px)}
  .ring{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:17px 10px;background:radial-gradient(circle at 50% 35%,#1b2a3c,#0d1520 68%);border:1px solid #2b3b50;border-radius:18px;box-shadow:0 20px 50px rgba(0,0,0,.25),inset 0 1px rgba(255,255,255,.045)}.ringwrap{position:relative;width:170px;height:170px}.ringwrap::after{content:"";position:absolute;inset:24px;border:1px solid rgba(255,255,255,.045);border-radius:50%}.ring svg{display:block;transform:rotate(-90deg);filter:drop-shadow(0 0 6px rgba(244,184,96,.18))}.ring svg circle:first-child{stroke:#26354a!important}.ringtxt{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column;z-index:1}.ringnum{font-size:47px;line-height:1;font-weight:760;letter-spacing:-.045em;font-variant-numeric:tabular-nums}.ringlbl{margin-top:6px;color:var(--muted);font:650 9.5px/1.2 var(--mono);letter-spacing:.14em;text-transform:uppercase}.ringcap{margin-top:12px;color:#78899f;font-size:11.5px;line-height:1.5;text-align:center}.ringcap b{color:#dce5f0;font-weight:650}
  .money{margin-bottom:17px;padding:17px 20px;background:var(--surface);border:1px solid var(--line);border-radius:12px;box-shadow:0 14px 36px rgba(0,0,0,.16)}.money h3{margin:0;color:#8494a9;font:650 10px/1.2 var(--mono);letter-spacing:.13em;text-transform:uppercase}.mrow{display:flex;align-items:center;gap:14px;margin-top:12px;font:12.5px/1.3 var(--mono)}.mrow .nm{width:134px;color:#91a0b3}.mrow .bar{height:12px;flex:1;overflow:hidden;background:#080d14;border:1px solid #253247;border-radius:4px}.mrow .bar i{display:block;height:100%;transition:width .6s ease}.mrow.p .bar i{background:linear-gradient(90deg,#248965,var(--green));box-shadow:0 0 10px rgba(77,215,160,.3)}.mrow.m .bar i{background:linear-gradient(90deg,#2b6fa5,var(--cyan));box-shadow:0 0 10px rgba(97,186,252,.3)}.mrow .dv{width:80px;text-align:right;color:#637288}.mrow .dv.moved{color:var(--green);font-weight:800}.mrow .v{width:126px;text-align:right;color:#eef4fb;font-weight:700}.still{margin-top:12px;color:#8fdcbf;font-size:12.5px}.still b{color:var(--green);font-variant-numeric:tabular-nums}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{padding:18px 20px;background:linear-gradient(160deg,#111b29,#0d141f);border:1px solid var(--line);border-radius:12px;box-shadow:0 14px 36px rgba(0,0,0,.16)}.card h3{margin:0 0 10px;color:#8494a9;font:650 10px/1.2 var(--mono);letter-spacing:.12em;text-transform:uppercase}.piece{display:grid;grid-template-columns:96px 1fr;gap:13px;padding:10px 0;border-bottom:1px solid #202d3f}.piece:last-child{border-bottom:0}.piece .k{font-size:13px;font-weight:750}.piece .d{color:#8695a9;font-size:12.5px}.piece .d code{padding:1px 4px;background:#080d14;border:1px solid #233148;border-radius:4px;color:#c2d2e5;font:11px var(--mono)}.kX{color:var(--violet)}.kA{color:#ff727d}.kW{color:var(--amber)}
  .ev{display:flex;gap:12px;padding:9px 0;border-bottom:1px solid #202d3f;font:11.5px/1.5 var(--mono)}.ev .kind{width:184px;flex:0 0 auto;font-weight:750}.ev .used{color:var(--green)}.ev .canc{color:var(--red)}.ev .meta{min-width:0;flex:1;color:#718197;word-break:break-all}.empty{padding:13px 0;color:#617087;font-size:12.5px}.cta{margin-top:12px;padding:13px 15px;background:#090f18;border:1px solid #29384c;border-radius:8px;color:#728198;font:11.5px/1.65 var(--mono)}.cta b{color:var(--amber)}a{color:var(--cyan);text-decoration:none}a:hover{text-decoration:underline}
  @media(max-width:1000px){body{padding:19px 18px 92px}.split{grid-template-columns:minmax(0,1fr) 220px minmax(0,1fr);gap:11px}.grid2{grid-template-columns:1fr}.rail{overflow-x:auto}.step{min-width:128px}.chain{text-align:left}}
  @media(max-width:720px){body{padding:13px 11px 92px}.brand{font-size:27px}.chain{width:100%;justify-content:space-between;gap:10px}.chain b{font-size:11px}.split{grid-template-columns:1fr}.ring{min-height:260px}.mrow{display:grid;grid-template-columns:1fr auto;gap:7px}.mrow .nm,.mrow .dv,.mrow .v{width:auto}.mrow .bar{grid-column:1/-1;grid-row:2}.mrow .dv{grid-column:1}.mrow .v{grid-column:2}.piece{grid-template-columns:1fr}.ev{display:block}.ev .kind{width:auto;margin-bottom:4px}}
`)

register('human', {
  name: 'Human in Control',
  note: 'A vivid human-first product story that makes the payer veto feel approachable, premium, and memorable.',
  arc: { cooling: '#ffd768', void: '#ff8aa0', settled: '#72e0b9', lapsed: '#c7c2df' },
}, `
  :root{--ink:#17152d;--muted:#696680;--line:#dcd9f0;--lav:#efedff;--paper:#fbfaff;--card:#fff;--purple:#5b50e6;--coral:#e44362;--green:#087f60;--yellow:#ffd768;--blue:#226bb3;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
  *,*::before,*::after{box-sizing:border-box}
  body{margin:0;min-height:100vh;background:radial-gradient(circle at 8% 5%,#ffe2d9 0,transparent 25%),radial-gradient(circle at 92% 7%,#ddd9ff 0,transparent 28%),var(--paper);color:var(--ink);font:15px/1.5 var(--sans);padding:26px 29px 94px}
  .wrap{max-width:1480px;margin:0 auto}
  .top{display:flex;align-items:flex-end;justify-content:space-between;gap:30px;flex-wrap:wrap;margin-bottom:20px;padding:17px 21px;background:rgba(255,255,255,.78);border:1px solid rgba(220,217,240,.9);border-radius:24px;box-shadow:0 14px 45px rgba(54,44,126,.07)}.brand{max-width:920px;font-size:32px;line-height:1.08;font-weight:760;letter-spacing:-.04em}.brand b{color:var(--purple);font-weight:800}.tag{margin-top:9px;color:var(--muted);font-size:13.5px}.tag code{padding:3px 7px;background:var(--lav);border-radius:999px;color:var(--purple);font:11px var(--mono)}
  .chain{display:flex;gap:25px;text-align:right;color:#85829b;font-size:10px;line-height:1.3;letter-spacing:.1em;text-transform:uppercase}.chain b{display:block;margin-top:5px;color:var(--ink);font-size:13px;letter-spacing:0;text-transform:none}.live::before{content:"";display:inline-block;width:8px;height:8px;margin-right:7px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px rgba(8,127,96,.1);animation:huBeat 1.8s infinite}@keyframes huBeat{50%{transform:scale(.7);box-shadow:0 0 0 9px rgba(8,127,96,0)}}
  .thesis{position:relative;margin:0 0 20px;padding:20px 25px 20px 74px;background:var(--ink);border-radius:18px;color:#d8d5ed;font-size:17px;box-shadow:0 13px 34px rgba(23,21,45,.13)}.thesis::before{content:"✓";position:absolute;left:22px;top:50%;display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:var(--yellow);color:var(--ink);font-weight:900;transform:translateY(-50%)}.thesis b{color:white}
  .rail{display:flex;gap:7px;margin:0 0 7px}.railnote{margin:0 0 20px;color:var(--muted);font-size:12.5px;text-align:center}.railnote i{color:var(--ink);font-style:normal;font-weight:700}
  .step{position:relative;flex:1;min-width:0;padding:12px 13px;background:#ebe9f4;border-radius:12px;color:#9995ac}.step .n{font-size:9.5px;line-height:1.2;letter-spacing:.1em;font-weight:800}.step .t{margin-top:3px;font-size:12px}.step.done{background:#e4f3ed;color:#527a6b}.step.done .t{color:#527a6b}.step.on{background:var(--lav);color:var(--purple);box-shadow:inset 0 0 0 2px #aca5ff}.step.on .t{color:var(--purple);font-weight:800}.step.on::after{content:"";position:absolute;right:10px;top:10px;width:9px;height:9px;border-radius:50%;background:var(--purple);animation:huBeat 1.4s infinite}.step.kill{background:#ffe8ec;color:var(--coral);box-shadow:inset 0 0 0 2px #f5a5b4}.step.kill .t{color:var(--coral);font-weight:800}.step.fin{background:#daf4e9;color:var(--green)}.step.fin .t{color:var(--green);font-weight:800}
  .split{display:grid;grid-template-columns:minmax(0,1fr) 260px minmax(0,1fr);gap:17px;align-items:stretch;margin-bottom:18px}.side{display:flex;flex-direction:column;min-width:0;padding:22px;background:var(--card);border:1px solid var(--line);border-radius:22px;box-shadow:0 16px 42px rgba(54,44,126,.075)}.side.merchant{background:linear-gradient(160deg,#fff 60%,#edf6ff)}.side.payer{background:linear-gradient(160deg,#fff 60%,#fff0f3)}
  .who{display:inline-flex;align-self:flex-start;padding:5px 9px;border-radius:999px;background:#eeedf5;color:#6d6982;font-size:10px;line-height:1.2;letter-spacing:.11em;text-transform:uppercase;font-weight:800}.side.merchant .who{background:#e6f2fc;color:#376c92}.side.payer .who{background:#ffe4ea;color:#a73349}.verdictline{min-height:37px;margin:10px 0 9px;font-size:21px;line-height:1.2;font-weight:780;letter-spacing:-.025em}.can{color:var(--green)}.cant{color:var(--coral)}.wait{color:#9a6810}.fnote{margin-top:6px;color:#78758d;font:11px/1.65 var(--mono)}.fnote b{color:#44405d}
  .quote{position:relative;margin-top:auto;padding:18px 18px 17px;background:#251f3d;border-radius:14px;color:#fff;box-shadow:0 12px 28px rgba(37,31,61,.18)}.quote::after{content:"×";position:absolute;right:14px;top:8px;color:#ff6680;font:700 28px/1 var(--sans)}.quote .lbl{padding-right:28px;color:#a9a3c3;font:9.5px/1.4 var(--mono);text-transform:uppercase}.quote .said{margin-top:9px;color:#ff9aaa;font:750 22px/1.27 var(--mono);letter-spacing:-.03em;word-break:break-word}.quote .prov{margin-top:10px;color:#8f89a9;font:10px/1.4 var(--mono)}.quote.ok .said{color:#79e5bd}
  button{width:100%;padding:14px 17px;border:0;border-radius:13px;font:800 13.5px/1.2 var(--sans);letter-spacing:.015em;cursor:pointer;transition:transform .15s,box-shadow .15s,filter .15s}button:disabled{opacity:.48;cursor:not-allowed}.bSettle{background:var(--purple);color:#fff;box-shadow:0 9px 20px rgba(91,80,230,.22)}.bSettle.blocked{background:#ebeaf1;color:#838095;box-shadow:none}.bCancel{background:var(--coral);color:#fff;box-shadow:0 9px 20px rgba(228,67,98,.2)}.bCancel:hover:not(:disabled){transform:translateY(-2px);filter:saturate(1.15)}
  .ring{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:17px 11px;background:linear-gradient(160deg,#655aff,#4c42d2);border-radius:30px;color:#fff;box-shadow:0 18px 42px rgba(91,80,230,.24)}.ringwrap{position:relative;width:170px;height:170px}.ring svg{display:block;transform:rotate(-90deg)}.ring svg circle:first-child{stroke:rgba(255,255,255,.2)!important}.ringtxt{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;flex-direction:column}.ringnum{font-size:49px;line-height:1;font-weight:800;letter-spacing:-.05em;font-variant-numeric:tabular-nums}.ringlbl{margin-top:6px;color:#dcd9ff;font-size:9.5px;line-height:1.2;letter-spacing:.15em;text-transform:uppercase;font-weight:750}.ringcap{margin-top:12px;color:#d2ceff;font-size:11.5px;line-height:1.5;text-align:center}.ringcap b{display:inline-block;margin:1px 0;padding:0 5px;border-radius:5px;background:white;color:var(--purple);font-weight:800}
  .money{margin-bottom:18px;padding:19px 22px;background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:0 14px 36px rgba(54,44,126,.065)}.money h3{margin:0;color:#7c7892;font-size:10.5px;line-height:1.2;letter-spacing:.14em;text-transform:uppercase}.mrow{display:flex;align-items:center;gap:14px;margin-top:12px;font:12.5px/1.3 var(--mono)}.mrow .nm{width:134px;color:#56526d}.mrow .bar{height:14px;flex:1;overflow:hidden;background:#eeedf6;border-radius:999px}.mrow .bar i{display:block;height:100%;border-radius:999px;transition:width .6s ease}.mrow.p .bar i{background:linear-gradient(90deg,#655aff,#9188ff)}.mrow.m .bar i{background:linear-gradient(90deg,#ff7a8f,#e44362)}.mrow .dv{width:79px;text-align:right;color:#8a879c}.mrow .dv.moved{color:var(--green);font-weight:800}.mrow .v{width:128px;text-align:right;color:var(--ink);font-weight:800}.still{display:inline-flex;align-items:center;gap:5px;margin-top:13px;padding:6px 10px;background:#e7f6f0;border-radius:999px;color:var(--green);font-size:12.5px}.still b{font-variant-numeric:tabular-nums}
  .grid2{display:grid;grid-template-columns:1.08fr .92fr;gap:17px}.card{padding:19px 21px;background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:0 14px 36px rgba(54,44,126,.065)}.card h3{margin:0 0 10px;color:#7d7992;font-size:10.5px;line-height:1.2;letter-spacing:.13em;text-transform:uppercase}.piece{display:grid;grid-template-columns:96px 1fr;gap:13px;padding:10px 0;border-bottom:1px solid #ebe9f5}.piece:last-child{border-bottom:0}.piece .k{font-size:13px;font-weight:850}.piece .d{color:#66627a;font-size:12.5px}.piece .d code{padding:2px 5px;background:#f0eff8;border-radius:5px;color:#37334f;font:11px var(--mono)}.kX{color:#6a4fb2}.kA{color:#d53d45}.kW{color:#9a6600}
  .ev{display:flex;gap:12px;padding:10px 0;border-bottom:1px solid #ebe9f5;font:11.5px/1.5 var(--mono)}.ev .kind{width:184px;flex:0 0 auto;font-weight:800}.ev .used{color:var(--green)}.ev .canc{color:var(--coral)}.ev .meta{min-width:0;flex:1;color:#7c7890;word-break:break-all}.empty{padding:13px 0;color:#918da2;font-size:13px}.cta{margin-top:12px;padding:14px 15px;background:#f1f0fa;border-radius:12px;color:#76728b;font:11.5px/1.65 var(--mono)}.cta b{color:var(--purple)}a{color:var(--blue);text-decoration:none}a:hover{text-decoration:underline}
  @media(max-width:1000px){body{padding:19px 17px 94px}.split{grid-template-columns:minmax(0,1fr) 220px minmax(0,1fr);gap:11px}.grid2{grid-template-columns:1fr}.rail{overflow-x:auto}.step{min-width:126px}.chain{text-align:left}}
  @media(max-width:720px){body{padding:13px 10px 94px}.top{border-radius:18px}.brand{font-size:27px}.chain{width:100%;justify-content:space-between;gap:9px}.chain b{font-size:11px}.thesis{padding:17px 17px 17px 60px}.thesis::before{left:16px}.split{grid-template-columns:1fr}.ring{min-height:270px}.mrow{display:grid;grid-template-columns:1fr auto;gap:7px}.mrow .nm,.mrow .dv,.mrow .v{width:auto}.mrow .bar{grid-column:1/-1;grid-row:2}.mrow .dv{grid-column:1}.mrow .v{grid-column:2}.piece{grid-template-columns:1fr}.ev{display:block}.ev .kind{width:auto;margin-bottom:4px}}
`)
